//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMaster
    {
        public int Id { get; set; }
        public string title { get; set; }
        public System.DateTime Date { get; set; }
        public string Location { get; set; }
        public int Duration { get; set; }
        public string Description { get; set; }
        public string Details { get; set; }
        public string Invite { get; set; }
        public string username { get; set; }
        public int Event_Type { get; set; }
    }
}
