// <auto-generated />
namespace book_reading_event.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class displaymodule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(displaymodule));
        
        string IMigrationMetadata.Id
        {
            get { return "202305010626572_displaymodule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
